// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using music_manager_starter.Data;

#nullable disable

namespace music_manager_start.Data.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20241119214529_DemoMigration")]
    partial class DemoMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("music_manager_starter.Data.Models.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("42e4b4d5-93bb-4e46-bb6e-c57de62e7f6e"),
                            Album = "When We All Fall Asleep, Where Do We Go?",
                            Artist = "Billie Eilish",
                            FilePath = "/images/be1.png",
                            Genre = "Pop",
                            Rating = 10,
                            Title = "When the Party's Over"
                        },
                        new
                        {
                            Id = new Guid("b7cc1c82-77e2-40d0-8bc2-d7e05962c0e3"),
                            Album = "The Great Escape",
                            Artist = "French Cassettes",
                            FilePath = "/images/pb.png",
                            Genre = "Indie",
                            Rating = 10,
                            Title = "Utah"
                        },
                        new
                        {
                            Id = new Guid("22aa6f84-06d8-4a0e-bdad-3000b35b5b5f"),
                            Album = "Twelve Carat Toothache",
                            Artist = "Post Malone",
                            FilePath = "/images/pm.png",
                            Genre = "Hip Hop",
                            Rating = 10,
                            Title = "Something Real"
                        },
                        new
                        {
                            Id = new Guid("5d7686e9-b672-43d5-aec2-4bb3ffd9b665"),
                            Album = "When We All Fall Asleep, Where Do We Go?",
                            Artist = "Billie Eilish",
                            FilePath = "/images/be1.png",
                            Genre = "Pop",
                            Rating = 10,
                            Title = "Bad Guy"
                        },
                        new
                        {
                            Id = new Guid("6134ece0-f465-4102-b5e6-54afaebc1c19"),
                            Album = "When We All Fall Asleep, Where Do We Go?",
                            Artist = "Billie Eilish",
                            FilePath = "/images/be1.png",
                            Genre = "Pop",
                            Rating = 10,
                            Title = "My Strange Addiction"
                        },
                        new
                        {
                            Id = new Guid("ba62c87f-5a86-4f9b-85b5-16ba4ad39e30"),
                            Album = "Hit Me Hard And Soft",
                            Artist = "Billie Eilish",
                            FilePath = "/images/be2.png",
                            Genre = "Pop",
                            Rating = 10,
                            Title = "Birds Of A Feather"
                        },
                        new
                        {
                            Id = new Guid("dd906bcb-12b7-4cb1-9231-603d4f544390"),
                            Album = "Hit Me Hard And Soft",
                            Artist = "Billie Eilish",
                            FilePath = "/images/be2.png",
                            Genre = "Pop",
                            Rating = 10,
                            Title = "The Greatest"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
