// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using music_manager_starter.Data;

#nullable disable

namespace music_manager_start.Data.Migrations
{
    [DbContext(typeof(DataDbContext))]
    partial class DataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("music_manager_starter.Data.Models.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("SongId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d228aaad-0923-4ba6-8797-4f1ddedbc78f"),
                            SongId = "42e4b4d5-93bb-4e46-bb6e-c57de62e7f6e",
                            rating = 10
                        },
                        new
                        {
                            Id = new Guid("8fd2d752-e973-46d7-9ec2-088ef7b18f19"),
                            SongId = "b7cc1c82-77e2-40d0-8bc2-d7e05962c0e3",
                            rating = 9
                        },
                        new
                        {
                            Id = new Guid("7ca7cf3d-811c-419f-8cb3-f77f0ad21982"),
                            SongId = "22aa6f84-06d8-4a0e-bdad-3000b35b5b5f",
                            rating = 8
                        },
                        new
                        {
                            Id = new Guid("e4719187-9084-4a4b-a622-159c06cfe2eb"),
                            SongId = "5d7686e9-b672-43d5-aec2-4bb3ffd9b665",
                            rating = 7
                        },
                        new
                        {
                            Id = new Guid("3f640e8e-2517-4a2a-86ae-527279888015"),
                            SongId = "6134ece0-f465-4102-b5e6-54afaebc1c19",
                            rating = 6
                        },
                        new
                        {
                            Id = new Guid("2051fcc5-c41f-46d5-87d3-2520c151df2a"),
                            SongId = "ba62c87f-5a86-4f9b-85b5-16ba4ad39e30",
                            rating = 5
                        },
                        new
                        {
                            Id = new Guid("244c3b6c-ff3a-4b50-bda0-432116176d17"),
                            SongId = "dd906bcb-12b7-4cb1-9231-603d4f544390",
                            rating = 4
                        },
                        new
                        {
                            Id = new Guid("1279430c-d55a-4a6e-a1ac-b12da285bdfe"),
                            SongId = "dd906bcb-12b7-4cb1-9231-603d4f544390",
                            rating = 2
                        });
                });

            modelBuilder.Entity("music_manager_starter.Data.Models.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("42e4b4d5-93bb-4e46-bb6e-c57de62e7f6e"),
                            Album = "When We All Fall Asleep, Where Do We Go?",
                            Artist = "Billie Eilish",
                            FilePath = "/images/be1.jpg",
                            Genre = "Pop",
                            Title = "When the Party's Over"
                        },
                        new
                        {
                            Id = new Guid("b7cc1c82-77e2-40d0-8bc2-d7e05962c0e3"),
                            Album = "The Great Escape",
                            Artist = "French Cassettes",
                            FilePath = "/images/fc.jpg",
                            Genre = "Indie",
                            Title = "Utah"
                        },
                        new
                        {
                            Id = new Guid("22aa6f84-06d8-4a0e-bdad-3000b35b5b5f"),
                            Album = "Twelve Carat Toothache",
                            Artist = "Post Malone",
                            FilePath = "/images/pm.png",
                            Genre = "Hip Hop",
                            Title = "Something Real"
                        },
                        new
                        {
                            Id = new Guid("5d7686e9-b672-43d5-aec2-4bb3ffd9b665"),
                            Album = "When We All Fall Asleep, Where Do We Go?",
                            Artist = "Billie Eilish",
                            FilePath = "/images/be1.jpg",
                            Genre = "Pop",
                            Title = "Bad Guy"
                        },
                        new
                        {
                            Id = new Guid("6134ece0-f465-4102-b5e6-54afaebc1c19"),
                            Album = "When We All Fall Asleep, Where Do We Go?",
                            Artist = "Billie Eilish",
                            FilePath = "/images/be1.jpg",
                            Genre = "Pop",
                            Title = "My Strange Addiction"
                        },
                        new
                        {
                            Id = new Guid("ba62c87f-5a86-4f9b-85b5-16ba4ad39e30"),
                            Album = "Hit Me Hard And Soft",
                            Artist = "Billie Eilish",
                            FilePath = "/images/be2.png",
                            Genre = "Pop",
                            Title = "Birds Of A Feather"
                        },
                        new
                        {
                            Id = new Guid("dd906bcb-12b7-4cb1-9231-603d4f544390"),
                            Album = "Hit Me Hard And Soft",
                            Artist = "Billie Eilish",
                            FilePath = "/images/be2.png",
                            Genre = "Pop",
                            Title = "The Greatest"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
