// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using music_manager_starter.Data;

#nullable disable

namespace music_manager_start.Data.Migrations
{
    [DbContext(typeof(DataDbContext))]
    partial class DataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("music_manager_starter.Data.Models.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f47c84f-4a7d-4e83-8b8f-1829f0eafca3"),
                            Album = "Spiritbox",
                            Artist = "Spiritbox",
                            FilePath = "/images/pb.png",
                            Genre = "Metal",
                            Rating = 10,
                            Title = "Circle With Me"
                        },
                        new
                        {
                            Id = new Guid("2a76a0b1-b3e1-4ff0-9aa5-5f5e4c81bc45"),
                            Album = "Canyon",
                            Artist = "Pony Bradshaw",
                            FilePath = "/images/pb.png",
                            Genre = "Folk",
                            Rating = 10,
                            Title = "Notes on a River Town"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
